# Generated by Django 5.2.15 on 2026-07-07 10:20

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Initialized'), (1, 'Uploaded'), (2, 'Failed')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
